Add Windows Dockerfile
UserOfficeProject/user-office-gateway pull request #16
Opened 2021-04-12 16:57 UTC by simonfernandes

This is for STFC use when generating the duo-frontend SDK

2021-04-12 17:16 UTC, mr-field requested changes

2021-04-12 17:16 UTC, mr-field commented on Dockerfile.dev.win
> +FROM docker-registry.devs.facilities.rl.ac.uk/bisapps-node:12-servercore${WINDOWS_VERSION}-1.0.0-SNAPSHOT
```suggestion
FROM docker-registry.devs.facilities.rl.ac.uk/bisapps-node:12-servercore${WINDOWS_VERSION}
```

The base image was recently renamed to this

2021-04-13 10:27 UTC, mr-field approved these changes

2021-04-16 11:07 UTC, TheCyalex approved these changes

2021-04-26 15:30 UTC, merged